---
title: 'RMarkdown:  In Class Assignment'
author: "Christian Armstrong"
date: "08/30/2022"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```

Reminder: There is a "Markdown Help" page available in RStudio.

## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.

# Your work here

## Wise words

"Today the crumbs, tomorrow the loaf, perhaps some day the whole damn boulangerie" - Jack Rackham(Season 3 of Black Sails) [link](https://black-sails.fandom.com/wiki/Bread)

## My semester

| Course Number | Course Title    | Instructor's Name   |
|---------------|-----------------|---------------------|
| **BIOL 1312** | *Envir. Bio.*   | Suzette Mouchaty    |
| **DATA 2401** | *Data Sci. 1*   | Katherine Shoemaker |
| **ECO 2301**  | *Economics 1*   | Shuang Xu           |
| **MATH 2305** | *Discrete Math* | Vien Nguyen         |

## I recommend

### Nipsey Hussle

> "I got my perfect form Straight out the eye Of this perfect storm I did mine, with a perfect score Don't waste time, We just work some more Rolls Royce raps, And my tone is Forbes Ima take it overboard"

1.  Blue Laces 2
2.  Between Us ft. K Camp
3.  4 in the Mornin
4.  That's How I Knew
5.  Clarity ft. Dave East and Bino Rideaux
